=== tericcabrel/mern-starter/server/public/apidoc/schemas/tasks/get-all/response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
   "id": "http://localhost/api-doc/schemas/",
    "type": "array",
    "description": "The list of task.",
    "items": {
      "type": "object",
      "properties": {
         "_id": {
          "type": "string",
          "description": "ID of the task"
        },
        "title": {
          "type": "string",
          "description": "Task title"
        },
        "description" : {
          "type": "string",
          "description": "Task description"
        },
         "status" : {
          "type": "string",
           "description": "Task status. Possible value: `Pending`, `Completed`, ``"
        },
        "date": {
          "type": "string",
          "description": "Time to execute the task"
        },
        "is_important": {
          "type": "boolean",
          "description": "Indicate the task importance"
        },
        "user": {
          "type": "string",
          "description": "Id of the creator of the task"
        },
        "created_at": {
          "type": "string",
          "description": "Task creation date"
        },
        "updated_at": {
          "type": "string",
          "description": "Task update date"
        }
      },
     "required": [ "_id", "title", "description", "status", "date", "is_important", "user", "created_at", "updated_at" ]
    }
    
}

=== tericcabrel/mern-starter/server/public/apidoc/examples/tasks/get-all/response.json
[
    {
      "_id": "5d31c351df1c9dfd93d25786",
      "title": "Test Application",
      "description": "QA testing on the whole application",
      "status": "Pending",
      "date": "2019-05-30 09:30:00",
      "is_important": true,
      "user": "5cee861d04d9f4214dc8dce6",
      "created_at": "2019-07-19 14:19:13.463",
      "updated_at": "2019-07-19 14:19:13.463"
    },
    {
      "_id": "5caa22a898eb5b14af3e93ec",
      "title": "Learn a Tutorial",
      "description": "Learn tutorial on microservice architectures",
      "status": "Completed",
      "date": "2019-05-30 09:30:00",
      "is_important": false,
      "user": "5cee861d04d9f4214dc8dce6",
      "created_at": "2019-07-19 14:19:13.463",
      "updated_at": "2019-07-19 14:19:13.463"
    }
]
