=== tericcabrel/mern-starter/server/public/apidoc/schemas/users/get-all/response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
   "id": "http://localhost/api-doc/schemas/",
    "type": "array",
    "description": "The list of users.",
    "items": {
      "type": "object",
      "properties": {
         "_id" : {
          "type": "string",
          "description": "User id"
        },
         "name": {
          "type": "string",
          "description": "User name"
        },
        "username" : {
          "type": "string",
          "description": "User name"
        },
         "email" : {
          "type": "string",
          "description": "User email address",
          "format": "email"
        },
        "gender": {
          "type": "string",
          "description": "User gender"
        },
        "confirmed": {
          "type": "boolean",
          "description": "Indciates if account is confirmed or not"
        },
        "avatar": {
          "type": "string",
          "description": "Path of the picture the user"
        }
      },
     "required": [ "_id", "name", "username", "email", "gender", "confirmed", "avatar"]
    }
    
}

=== tericcabrel/mern-starter/server/public/apidoc/examples/users/get-all/response.json
[
    {
      "_id": "5d31d9d0fd4fc002e68d8f93",
      "name" : "John DOE",
      "username" : "jndoe",
      "email" : "user@example.com",
      "gender": "M",
      "confirmed": true,
      "avatar": "https://api.starter.com/uploads/1557234445-user.png"
    },
    {
      "_id": "5caa22a898eb5b14af3e93ec",
      "name" : "Alice BOB",
      "username" : "alibob",
      "email" : "alibob@example.com",
      "gender": "F",
      "confirmed": true,
      "avatar": "https://api.starter.com/uploads/1557398373-user.png"
    }
]
